//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18051.
// 
#pragma warning disable 1591

namespace WSKorisnik.WSProxies {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSoap", Namespace="http://wsdiplomski.net/")]
    public partial class WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getKategorijeOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPostsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getKategorijeJsonOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPostsJsonOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService() {
            this.Url = global::WSKorisnik.Properties.Settings.Default.WSKorisnik_WSProxies_WebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getKategorijeCompletedEventHandler getKategorijeCompleted;
        
        /// <remarks/>
        public event getPostsCompletedEventHandler getPostsCompleted;
        
        /// <remarks/>
        public event getKategorijeJsonCompletedEventHandler getKategorijeJsonCompleted;
        
        /// <remarks/>
        public event getPostsJsonCompletedEventHandler getPostsJsonCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://wsdiplomski.net/getKategorije", RequestNamespace="http://wsdiplomski.net/", ResponseNamespace="http://wsdiplomski.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Kategorija[] getKategorije() {
            object[] results = this.Invoke("getKategorije", new object[0]);
            return ((Kategorija[])(results[0]));
        }
        
        /// <remarks/>
        public void getKategorijeAsync() {
            this.getKategorijeAsync(null);
        }
        
        /// <remarks/>
        public void getKategorijeAsync(object userState) {
            if ((this.getKategorijeOperationCompleted == null)) {
                this.getKategorijeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetKategorijeOperationCompleted);
            }
            this.InvokeAsync("getKategorije", new object[0], this.getKategorijeOperationCompleted, userState);
        }
        
        private void OngetKategorijeOperationCompleted(object arg) {
            if ((this.getKategorijeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getKategorijeCompleted(this, new getKategorijeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://wsdiplomski.net/getPosts", RequestNamespace="http://wsdiplomski.net/", ResponseNamespace="http://wsdiplomski.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Post[] getPosts(string nazivKategorije) {
            object[] results = this.Invoke("getPosts", new object[] {
                        nazivKategorije});
            return ((Post[])(results[0]));
        }
        
        /// <remarks/>
        public void getPostsAsync(string nazivKategorije) {
            this.getPostsAsync(nazivKategorije, null);
        }
        
        /// <remarks/>
        public void getPostsAsync(string nazivKategorije, object userState) {
            if ((this.getPostsOperationCompleted == null)) {
                this.getPostsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPostsOperationCompleted);
            }
            this.InvokeAsync("getPosts", new object[] {
                        nazivKategorije}, this.getPostsOperationCompleted, userState);
        }
        
        private void OngetPostsOperationCompleted(object arg) {
            if ((this.getPostsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPostsCompleted(this, new getPostsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://wsdiplomski.net/getKategorijeJson", RequestNamespace="http://wsdiplomski.net/", ResponseNamespace="http://wsdiplomski.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Kategorija[] getKategorijeJson() {
            object[] results = this.Invoke("getKategorijeJson", new object[0]);
            return ((Kategorija[])(results[0]));
        }
        
        /// <remarks/>
        public void getKategorijeJsonAsync() {
            this.getKategorijeJsonAsync(null);
        }
        
        /// <remarks/>
        public void getKategorijeJsonAsync(object userState) {
            if ((this.getKategorijeJsonOperationCompleted == null)) {
                this.getKategorijeJsonOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetKategorijeJsonOperationCompleted);
            }
            this.InvokeAsync("getKategorijeJson", new object[0], this.getKategorijeJsonOperationCompleted, userState);
        }
        
        private void OngetKategorijeJsonOperationCompleted(object arg) {
            if ((this.getKategorijeJsonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getKategorijeJsonCompleted(this, new getKategorijeJsonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://wsdiplomski.net/getPostsJson", RequestNamespace="http://wsdiplomski.net/", ResponseNamespace="http://wsdiplomski.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Post[] getPostsJson(string nazivKategorije) {
            object[] results = this.Invoke("getPostsJson", new object[] {
                        nazivKategorije});
            return ((Post[])(results[0]));
        }
        
        /// <remarks/>
        public void getPostsJsonAsync(string nazivKategorije) {
            this.getPostsJsonAsync(nazivKategorije, null);
        }
        
        /// <remarks/>
        public void getPostsJsonAsync(string nazivKategorije, object userState) {
            if ((this.getPostsJsonOperationCompleted == null)) {
                this.getPostsJsonOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPostsJsonOperationCompleted);
            }
            this.InvokeAsync("getPostsJson", new object[] {
                        nazivKategorije}, this.getPostsJsonOperationCompleted, userState);
        }
        
        private void OngetPostsJsonOperationCompleted(object arg) {
            if ((this.getPostsJsonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPostsJsonCompleted(this, new getPostsJsonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdiplomski.net/")]
    public partial class Kategorija {
        
        private string idKategorijeField;
        
        private string nazivKategorijeField;
        
        /// <remarks/>
        public string idKategorije {
            get {
                return this.idKategorijeField;
            }
            set {
                this.idKategorijeField = value;
            }
        }
        
        /// <remarks/>
        public string nazivKategorije {
            get {
                return this.nazivKategorijeField;
            }
            set {
                this.nazivKategorijeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdiplomski.net/")]
    public partial class Post {
        
        private string naslovField;
        
        private string linkKaPostuField;
        
        /// <remarks/>
        public string Naslov {
            get {
                return this.naslovField;
            }
            set {
                this.naslovField = value;
            }
        }
        
        /// <remarks/>
        public string LinkKaPostu {
            get {
                return this.linkKaPostuField;
            }
            set {
                this.linkKaPostuField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getKategorijeCompletedEventHandler(object sender, getKategorijeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getKategorijeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getKategorijeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Kategorija[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Kategorija[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getPostsCompletedEventHandler(object sender, getPostsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPostsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPostsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Post[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Post[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getKategorijeJsonCompletedEventHandler(object sender, getKategorijeJsonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getKategorijeJsonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getKategorijeJsonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Kategorija[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Kategorija[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getPostsJsonCompletedEventHandler(object sender, getPostsJsonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPostsJsonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPostsJsonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Post[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Post[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591